import { Inter } from "next/font/google";
import "./globals.css";
import { Metadata } from "next"



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    absolute: "",
    default: "Pratham",
    template: "%s | Pratham",
  },
  description: "Generated by create next app",
  icons: {
    icon:['/favicon.ico']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white text-black min-h-screen bg-no-repeat`}>
        
        {children}
        </body>
    </html>
  );
}